version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8080:8080"
    environment:
      - DEBUG=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    volumes:
      - ./frontend:/usr/src/app:delegated
      - /usr/src/app/node_modules/

    ports:
      - "5173:5173"

    environment:
      - CHOKIDAR_USEPOLLING=true
